[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[context.production.environment]
  OPENROUTER_API_KEY = "sk-or-your-api-key"  # optional, better set it via dashboard
